### ISSUE TITLE
postinstall fails

### ISSUE THREAD

**Issue by ildella** [goldylucks/react-native-build-utils#1]
Hi there. Found your blog post about this, would be really useful, unfortunately I have an issue, I guess after more than a year something changed in the default react-native android app. 

Maybe there's a better approach today? 
If not this is the error, I'll try to debug it more now. 

```
> node scripts/postinstall

/appfolder/node_modules/react-native-build-utils/lib/setupGradle.js:21
      fs.readdir(pathToDir, function getAppDirNameCb (err, [appDirName]) {
                                                     ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at getAppDirNameCb (/appfolder/node_modules/react-native-build-utils/lib/setupGradle.js:21:54)
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by goldylucks** [comment]
feel free to take over this repo man, I'm not maintaining it anymore :)

**Comment by ildella** [comment]
I guessed so :) 
Still too new to the whole thing, need to understand if a project like this is really needed as I am experimenting with fastlane maybe there's a way to achieve this with that. 
Thanks for answering.

**Comment by goldylucks** [comment]
@ildella I'm closing this issue as it seems stale. Feel free to supply more details and reopen it.

**Comment by laurent22** [comment]
Having the exact same issue.
